create table notes(
  id integer primary key generated by default as identity,
  name text not null,
  content text not null,
  folder integer references folders(id) on delete cascade not null,
  date_published timestamp with time zone default now() not null
);